### ISSUE TITLE
Breaking usage of internal PokiSDK API

### ISSUE THREAD

**Issue by erikdubbelboer** [AvixGames/poki-c3-plugin#1]
This plugin seems to use internal undocumented PokiSDK APIs. Specifically `PokiSDK.SDK.adTimings`. All of `PokiSDK.SDK` can be changed at any moment without warning. We recently did this and broke all games using this plugin. We have temporarily restored `PokiSDK.SDK.adTimings` but it can be changed again at any moment.

Can you please remove all uses of `PokiSDK.SDK`.

I'm not sure I understand exactly you are using it for. Maybe I can help with some officially supported APIs instead.

I don't know what `this.PostToRuntime("SetCommercialBreakConstraint",{constrained:false});` does or why you sometimes do `PokiSDK.SDK.adTimings.timings.startAdsAfter+10`?

It seems like this code is used to only pause the game when an actual commercial break request is happening: https://github.com/AvixGames/poki-c3-plugin/blob/ad8e10c9e591b6472a15264e25c293f8b692c37a/c3runtime/domSide.js#L102-L103
I understand the use case here and will see if we can officially support something like this. For now I would just always pause the game. If nothing happens it will resume right away anyways.

If you need any help with this please let me know!

**Comment by erikdubbelboer** [comment]
Fixed in https://github.com/skymen/poki-c3-plugin which people should use now.

**Comment by pacoelayudante** [comment]
Thank you for your report, I'm sorry I was not following closely this repository.
I'll check and apply your fix as soon as I have a moment to review it.
